### ISSUE TITLE
dmenu bind?

### ISSUE THREAD

**Issue by kaihendry** [janza/wl-clipboard-history#1]
Hi! Do you have a way to get the paste in the clipboard like `clipd menu`?

https://mpov.timmorgan.org/clipboard-history-in-sway-window-manager/

**Comment by janza** [comment]
Would this work for you? https://github.com/janza/wl-clipboard-history/blob/master/contrib/dmenu-wrapper

**Comment by kaihendry** [comment]
Thanks!
