### ISSUE TITLE
Stops working after awhile?

### ISSUE THREAD

**Issue by kaihendry** [janza/wl-clipboard-history#2]
Number of issues for me on Arch:

* When I copy I get a window popup and disappear... very jarring
* It just stops working after a while

Made a screencast https://s.natalian.org/2019-04-02/wl-clipboard-history.mp4

**Comment by janza** [comment]
The popup window thing is probably related to [wl-clipboard](https://github.com/bugaevc/wl-clipboard/issues/24)
Not sure why it would stop working after a while though...
