### ISSUE TITLE
Switch to using wl-paste --watch mode

### ISSUE THREAD

**Issue by bugaevc** [janza/wl-clipboard-history#5]
Please check out https://github.com/bugaevc/wl-clipboard/issues/39#issuecomment-528948344 and https://github.com/bugaevc/wl-clipboard/issues/59 and https://github.com/yory8/clipman/issues/1 and implement something similar in wl-clipboard-history, so that we can avoid relying on hacks :smile:

**Comment by janza** [comment]
Thanks! The new option works well, no hacks needed anymore

**Comment by bugaevc** [comment]
Yay! 😀
